version: "3.9"

services:
  database:
    image: "ghcr.io/not4pedro/taranis-dev-database:e2e-test-db"
    ports:
      - "${TARANIS_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-taranis}"
      POSTGRES_USER: "${DB_USER:-taranis}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-supersecret}"
    command: ["postgres", "-c", "shared_buffers=${DB_SHARED_BUFFERS:-64MB}", "-c", "max_connections=${DB_MAX_CONNECTIONS:-1000}"]
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER:-taranis} -d ${DB_DATABASE:-taranis}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - "database_data:/var/lib/postgresql/data"

  rabbitmq:
    image: "rabbitmq:${RABBITMQ_TAG:-3-management-alpine}"
    ports:
      - "${TARANIS_RABBITMQ_PORT:-5672}:5672"
      - "${TARANIS_RABBITMQ_MGMT_PORT:-15672}:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq/"
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-taranis}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-supersecret}"

volumes:
  database_data:
  rabbitmq_data:
