version: "3.9"

x-logging: 
      &default-logging
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

services:
  database:
    image: "postgres:${POSTGRES_TAG}"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "taranis-ng"
      POSTGRES_USER: "taranis-ng"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: ["postgres", "-c", "shared_buffers=${DB_SHARED_BUFFERS}", "-c", "max_connections=${DB_MAX_CONNECTIONS}"]
    volumes:
      - "database_data:/var/lib/postgresql/data"
    logging: *default-logging

  core:
    depends_on: 
      - "database"
    restart: unless-stopped
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-core:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.core
#   ports: 
#     - "5000:80"
    environment: 
      DB_URL: "database"
      DB_DATABASE: "taranis-ng"
      DB_USER: "taranis-ng"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_POOL_SIZE: 100
      DB_POOL_RECYCLE: 300
      DB_POOL_TIMEOUT: 5

      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      OPENID_LOGOUT_URL: "${TARANIS_NG_HTTPS_URI}"
      WORKERS_PER_CORE: "1"
      TARANIS_NG_AUTHENTICATOR: "openid"

      TARANIS_NG_KEYCLOAK_URL: "http://${KEYCLOAK_DOMAIN}"
      TARANIS_NG_KEYCLOAK_INTERNAL_URL: "http://${KEYCLOAK_DOMAIN}/"

      CVE_UPDATE_FILE: "${CVE_UPDATE_FILE}"
      CPE_UPDATE_FILE: "${CPE_UPDATE_FILE}"

      DEBUG: "true"
      LOG_LEVEL: "debug"
    labels:
      traefik.enable: "true"
      traefik.http.services.taranis-api.loadbalancer.server.port: "80"

      traefik.http.routers.taranis-api-443.entrypoints: "websecure"
      traefik.http.routers.taranis-api-443.rule: "PathPrefix(`/api/`)"
      traefik.http.routers.taranis-api-443.tls: "true"
      traefik.http.routers.taranis-api-443.tls.domains[0].main: "${TARANIS_NG_HOSTNAME}"
      traefik.http.routers.taranis-api-443.service: "taranis-api"

      traefik.http.routers.taranis-sse-443.entrypoints: "websecure"
      traefik.http.routers.taranis-sse-443.rule: "PathPrefix(`/sse`)"
      traefik.http.routers.taranis-sse-443.tls: "true"
      traefik.http.routers.taranis-sse-443.tls.domains[0].main: "${TARANIS_NG_HOSTNAME}"
      traefik.http.routers.taranis-sse-443.service: "taranis-api"

    volumes:
      - "core_data:/data"
    logging: *default-logging

  bots:
    depends_on:
      core:
        condition: service_healthy
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-bots:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.bots
    environment:
      API_KEY: "${API_KEY}"
      TARANIS_NG_CORE_URL: "http://core/api/v1"
      TARANIS_NG_CORE_SSE: "http://core/sse"
      WORKERS_PER_CORE: "1"
    logging: *default-logging
    
  collectors:
    depends_on:
      core:
        condition: service_healthy
    restart: unless-stopped
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-collectors:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.collectors
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "${API_KEY}"
      WORKERS_PER_CORE: "1"
      DEBUG: "true"
    ports:
      - "5001:80"
    volumes:
      - "collector_storage:/app/storage"
    logging: *default-logging
    
  presenters:
    depends_on:
      core:
        condition: service_healthy
    restart: unless-stopped
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-presenters:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.presenters
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "${API_KEY}"
      WORKERS_PER_CORE: "1"
    ports:
      - "5002:80"
    volumes:
      - "presenters_templates:/app/templates"
    logging: *default-logging
    
  publishers:
    depends_on:
      core:
        condition: service_healthy
    restart: unless-stopped
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-publishers:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.publishers
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "${API_KEY}"
      WORKERS_PER_CORE: "1"
    ports:
      - "5003:80"
    logging: *default-logging

  gui:
    depends_on:
      - "core"
    restart: unless-stopped
    image: "${DOCKER_IMAGE_NAMESPACE}/taranis-ng-gui:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.gui
#    ports: 
#      - "8080:80"
    environment:
      NGINX_WORKERS: "4"
      NGINX_CONNECTIONS: "16"
      VUE_APP_TARANIS_NG_URL: "${TARANIS_NG_HTTPS_URI}"
      VUE_APP_TARANIS_NG_CORE_API: "${TARANIS_NG_HTTPS_URI}/api/v1"
      VUE_APP_TARANIS_NG_CORE_SSE: "${TARANIS_NG_HTTPS_URI}/sse"
      VUE_APP_TARANIS_NG_LOCALE: en
      VUE_APP_TARANIS_NG_LOGIN_URL: http://${KEYCLOAK_DOMAIN}/api/auth/login
      VUE_APP_TARANIS_NG_LOGOUT_URL: http://${KEYCLOAK_DOMAIN}/api/auth/logout
    labels:
      traefik.enable: "true"
      traefik.http.services.taranis-gui.loadbalancer.server.port: "80"

      traefik.http.middlewares.redirect-to-443.redirectscheme.scheme: "https"
      traefik.http.middlewares.redirect-to-443.redirectscheme.port: "${TARANIS_NG_HTTPS_PORT}"

      traefik.http.routers.taranis-gui-80.entrypoints: "web"
      traefik.http.routers.taranis-gui-80.rule: "PathPrefix(`/`)"
      traefik.http.routers.taranis-gui-80.middlewares: "redirect-to-443"

      traefik.http.routers.taranis-gui-443.entrypoints: "websecure"
      traefik.http.routers.taranis-gui-443.rule: "PathPrefix(`/`)"
      traefik.http.routers.taranis-gui-443.tls: "true"
      traefik.http.routers.taranis-gui-443.tls.domains[0].main: "${TARANIS_NG_HOSTNAME}"
      traefik.http.routers.taranis-gui-443.service: "taranis-gui"
    logging: *default-logging

  keycloak_database:
    image: "postgres:${POSTGRES_TAG}"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "keycloak_database_data:/var/lib/postgresql/data"
    logging: *default-logging

  keycloak:
    image: "quay.io/keycloak/keycloak:${KEYCLOAK_TAG}"
    restart: unless-stopped
    depends_on:
      - database
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      DB_VENDOR: POSTGRES
      DB_ADDR: "keycloak_database"
      DB_SCHEMA: public
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
    labels:
      traefik.enable: "true"
      traefik.http.services.keycloak.loadbalancer.server.port: "8080"

      traefik.http.routers.keycloak.entrypoints: "web"
      traefik.http.routers.keycloak.rule: "Host(`${KEYCLOAK_DOMAIN}`)"
      traefik.http.routers.keycloak.service: "keycloak"
    logging: *default-logging

  traefik:
    depends_on:
      - "gui"
      - "core"
    restart: unless-stopped
    image: "traefik:latest"
    ports: 
      - "${TARANIS_NG_HTTP_PORT}:80"
      - "${TARANIS_NG_HTTPS_PORT}:443"
      - "${TRAEFIK_MANAGEMENT_PORT}:9090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/etc/traefik:ro"
      - "./tls:/opt/certs"
    logging: *default-logging


volumes:
  database_data:
  keycloak_database_data:
  core_data:
  presenters_templates:
  collector_storage:
